### ISSUE TITLE
neofs-cli has command set-status 'online' which does not set the node online

### ISSUE THREAD

**Issue by EliChin** [nspcc-dev/neofs-node#831]
`neofs-cli control`  has command `set-status` with two given flags -- 'offline' and 'online'. `set-status --status 'offline'` works properly and excludes the node from the netmap. At the same time, `set-status --status 'online'` does not return the node to the netmap; although, upon its execution it states that `Network status update request successfully sent.`

Is there any point in having this 'online' flag if it does not provide the result that may be expected by a user (i.e. returning the node to the netmap)?

**Comment by alexvanin** [comment]
Switching node offline / online has multiple use cases:
- make a backup of the storage engine files,
- update storage node attributes.

So this is a viable command, let's see why it didn't work as expected.

**Comment by EliChin** [comment]
Actually, a node can be switched offline/online, but it seems to be an unstable process. Sometimes it is not switched offline (online, consequently) whatever number of epochs I tick and whatever waiting period is set.

**Comment by carpawell** [comment]
It seems like it can be associated with Notary requests with the same TX hashes(since we do not use unique `nonce` for them)

**Comment by carpawell** [comment]
@alexvanin, @EliChin, I think it can be closed, since it was fixed in `v0.25.0` release as I understand

**Comment by EliChin** [comment]
The new 0.25.0 release did improve the situation. However, once in 10-15 times test still fails for a node doesn't go offline.

**Comment by carpawell** [comment]
also, it can be associated with SN running out of notary deposits

@EliChin, after test fail SN loses the ability to go offline/online at all? does it fail only in notary-enabled environmental?

**Comment by alexvanin** [comment]
> @carpawell My last test failed after the node wasn't set offline. Then, I tried to set it offline manually, but got this result: `rpc error: rpc error: code = Aborted desc = could not invoke smart contract: could not invoke method (updateState): failed to submit notary request: Block or transaction validation failed. (-504) - insufficient funds - %!s(<nil>)` My environment is always notary-enabled.

Try to do it again after https://github.com/nspcc-dev/neofs-dev-env/pull/133 dev-env update. Should be fixed now.

**Comment by alexvanin** [comment]
I tried 20 `netmap_control.robot` consecutive runs on a fresh dev-env environment and it works just fine. 

```
$ for i in {1..20}; do robot --outputdir artifacts/ robot/testsuites/integration/network/netmap_control.robot; done
```

Anyway `insufficient funds` error is an environment configuration error, CLI command works as expected.
